### PR TITLE
[packer] add anti-upx unpacking for pe

### PR DESCRIPTION
**Pull request by Tatsuya-hasegawa**
Hello, fr0gger.

Instead of the previous elf PR,
I made PE version about anti-upx unpacking with my Yara rule.
Thanks in advance.

### CODE REVIEW

**Comment by fr0gger** [comment]
Nice, I merge to the main database thanks :)

**Review by fr0gger — APPROVED** [review]

**Comment by Tatsuya-hasegawa** [comment]
Thank you for merging. My pleasure sir!

**Comment by Tatsuya-hasegawa** [comment]
Hello @fr0gger 

I hope you are being well.
Unfortunately, my yara rule for Anti-UPX is not shown on your renewal site.
 https://unprotect.it/technique/anti-upx-unpacking/
 
Could you append it ? 
In addition, I don't know why this PE is "closed" not "merged".  🤔

**Comment by fr0gger** [comment]
Done thanks

**Comment by fr0gger** [comment]
Done thanks

**Pull request closed without merging**
